name: Add Contributors

on:
  pull_request:
    types: [closed]

jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add contributor
        uses: all-contributors/add-contributors-action@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.event.pull_request.user.login }}
          contribution: 'code'
